/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.silviowangler.mapstruct;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
